# Generated by Django 5.1.3 on 2024-12-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='resourceImg',
            field=models.ImageField(null=True, upload_to='resource_images/'),
        ),
    ]
