# Generated by Django 5.1.3 on 2024-12-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_resourceimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='resourceImg',
            field=models.ImageField(blank=True, null=True, upload_to='resource_images/'),
        ),
    ]
