# Generated by Django 5.1.3 on 2024-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productrequest_delete_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
