# Generated by Django 5.1.3 on 2024-12-08 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productrequest_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salehistory',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='salehistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salehistory',
            name='seller',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
        migrations.DeleteModel(
            name='SaleHistory',
        ),
    ]
