# Generated by Django 5.1.3 on 2024-12-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_salehistory_buyer_remove_salehistory_product_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='name',
        # ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='defaultuser', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
