# Generated by Django 5.1.3 on 2024-12-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_salehistory_buyer_remove_salehistory_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
