# Generated by Django 5.1.3 on 2024-12-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='unknownuser', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
