# Generated by Django 5.1.3 on 2025-01-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_name_user_username'),
        ('api', '0012_user_username'),
    ]

    operations = [
    ]
